json.user_id                                @profile.user_id
json.first_name                             @profile.first_name
json.middle_name                            @profile.middle_name
json.last_name                              @profile.last_name
json.extension_name                         @profile.extension_name
json.gender                                 @profile.gender.id
json.house                                  @profile.house
json.street                                 @profile.street
json.brgy                                   @profile.barangay
json.region                                 @profile.address.region.id
json.municipality                           @profile.address.municipality.id
json.province                               @profile.address.province.id
json.user_contact_number                    @profile.user_contact_number
json.dob                                    @profile.dob
json.religion                               @profile.religion
json.civil_status                           @profile.civil_status.id
json.spouse_name                            @profile.spouse_name
json.mother_name                            @profile.mother_name
json.household_head                         @profile.household_head
json.household_name                         @profile.household_name
json.household_head_relationship            @profile.household_head_relationship
json.numbers_household_member               @profile.numbers_household_member
json.education_attaintments                 @profile.education_attaintment.id
json.numbers_of_male                        @profile.numbers_of_male
json.numbers_of_female                      @profile.numbers_of_female
json.pwd                                    @profile.pwd
json.four_p_beneficiary                     @profile.four_p_beneficiary
json.with_government_id                     @profile.with_government_id
json.government_number                      @profile.government_id
json.member_association                     @profile.member_association
json.association_id                         @profile.association_id
json.indigenous_group                       @profile.indigenous_group
json.indigenous_id                          @profile.indigenous_id
json.person_to_notify                       @profile.emergency_person_name
json.emergency_person_number                @profile.emergency_person_number
json.agrarian                               @profile.agrarian
json.ref_number                             @profile.ref_number
json.place_of_birth                         @profile.place_of_birth
# json.photo                                 polymorphic_url(@profile.avatar)