# MySQL. Versions 5.5.8 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#

default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  database: MeshliumDB
  username: root
  password: elite
  host: 10.10.10.1
  port: 3306

meshDb:
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  host: 10.10.10.1
  port: 3306
  username: sslroot
  password: libelium2007
  database: MeshliumDB
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: MeshliumDB
test:
  <<: *default
  database: MeshliumDB_test

production:
  <<: *default
  database: MeshliumDB_prod
  username: sslroot
  password: MeshliumDB
  host: localhost

# default: &default
#   adapter: mysql2
#   encoding: utf8
#   host: <%= ENV["DB_HOST"] %>
#   username: <%= ENV["DB_USER"] %>
#   password: <%= ENV["DB_PASSWORD"] %>
#   port: <%= ENV["DB_PORT"] %>
#   wait_timeout: 300
#   pool: 5

# development:
#   <<: *default
#   database: <%= ENV["DB_NAME"] %>
# test:
#   <<: *default
#   database: <%= ENV["DB_TEST"] %>

# production:
#   <<: *default
#   database: <%= ENV["DB_NAME"] %>
  
# biomark_db:
#   <<: *default
#   database: <%= ENV["FARMJUAN_DB_NAME"] %>

